"""Validation, inheritance, and rendering for server-managed output rules."""
from __future__ import annotations

import json
from copy import deepcopy
from typing import Any

DEFAULT_RULES: dict[str, Any] = {
    "preamble": "none",
    "explanations": "on_request",
    "summary": "short",
    "tool_updates": "errors_only",
    "show_diff_only": True,
    "echo_unchanged_code": False,
    "require_evidence": False,
    "max_response_tokens": 800,
    "directives": [],
}
ENUM_RULES = {
    "preamble": {"none", "brief", "detailed"},
    "explanations": {"never", "on_request", "always"},
    "summary": {"none", "short", "detailed"},
    "tool_updates": {"none", "errors_only", "milestones", "all"},
}
KNOWN_RULES = set(DEFAULT_RULES)


def validate_rules(rules: dict[str, Any]) -> dict[str, Any]:
    unknown = set(rules) - KNOWN_RULES
    if unknown:
        raise ValueError(f"Unknown output rule(s): {', '.join(sorted(unknown))}")
    checked = deepcopy(rules)
    for key, allowed in ENUM_RULES.items():
        if key in checked and checked[key] not in allowed:
            raise ValueError(f"{key} must be one of: {', '.join(sorted(allowed))}")
    for key in ("show_diff_only", "echo_unchanged_code", "require_evidence"):
        if key in checked and not isinstance(checked[key], bool):
            raise ValueError(f"{key} must be a boolean")
    if "max_response_tokens" in checked:
        value = checked["max_response_tokens"]
        if not isinstance(value, int) or isinstance(value, bool) or not 128 <= value <= 8192:
            raise ValueError("max_response_tokens must be an integer between 128 and 8192")
    if "directives" in checked and (
        not isinstance(checked["directives"], list)
        or not all(isinstance(item, str) for item in checked["directives"])
    ):
        raise ValueError("directives must be a list of strings")
    return checked


def resolve_rules(base: dict[str, Any], overrides: dict[str, Any]) -> tuple[dict[str, Any], dict[str, str]]:
    resolved = deepcopy(validate_rules(base))
    checked_overrides = validate_rules(overrides)
    provenance = {key: "global" for key in resolved}
    for key, value in checked_overrides.items():
        resolved[key] = deepcopy(value)
        provenance[key] = "project"
    return resolved, provenance


def encode_rules(rules: dict[str, Any]) -> str:
    return json.dumps(validate_rules(rules), separators=(",", ":"), ensure_ascii=True)


def decode_rules(value: str) -> dict[str, Any]:
    decoded = json.loads(value)
    if not isinstance(decoded, dict):
        raise TypeError("Stored output rules must be an object")
    return validate_rules(decoded)


def render_markdown(rules: dict[str, Any], *, base_profile: str, version: int, project_id: int | None) -> str:
    scope = f"project {project_id}" if project_id is not None else "global"
    lines = [
        "<!-- CGA-MANAGED: server output rules; do not edit this file as a source of truth. -->",
        f"# Output Rules ({scope}, profile: {base_profile}, version: {version})",
        "",
        "Apply these rules to the final response:",
        f"- Preamble: `{rules['preamble']}`.",
        f"- Explanations: `{rules['explanations']}`.",
        f"- Summary: `{rules['summary']}`.",
        f"- Tool updates: `{rules['tool_updates']}`.",
        f"- Show only changed code when applicable: `{str(rules['show_diff_only']).lower()}`.",
        f"- Do not echo unchanged code: `{str(rules['echo_unchanged_code']).lower()}`.",
        f"- Evidence required: `{str(rules['require_evidence']).lower()}`.",
        f"- Soft response target: `{rules['max_response_tokens']} tokens`.",
    ]
    if rules["directives"]:
        lines.append("- Additional directives:")
        lines.extend(f"  - {directive}" for directive in rules["directives"])
    return "\n".join(lines) + "\n"
