[target.x86_64-pc-windows-msvc]
rustflags = [
	"-C", "target-feature=+crt-static",
	"-C", "control-flow-guard=checks",
	"-C", "link-arg=/DYNAMICBASE",
	"-C", "link-arg=/HIGHENTROPYVA",
	"-C", "link-arg=/NXCOMPAT",
	"-C", "link-arg=/CETCOMPAT",
	"-C", "link-arg=/guard:cf",
	"-C", "link-arg=/DEBUG:NONE",
	"-C", "link-arg=/Brepro",
	"-C", "link-arg=/OPT:REF",
	"-C", "link-arg=/OPT:ICF",
]

[target.aarch64-pc-windows-msvc]
rustflags = [
	"-C", "target-feature=+crt-static",
	"-C", "control-flow-guard=checks",
	"-C", "link-arg=/DYNAMICBASE",
	"-C", "link-arg=/HIGHENTROPYVA",
	"-C", "link-arg=/NXCOMPAT",
	"-C", "link-arg=/CETCOMPAT",
	"-C", "link-arg=/guard:cf",
	"-C", "link-arg=/DEBUG:NONE",
	"-C", "link-arg=/Brepro",
	"-C", "link-arg=/OPT:REF",
	"-C", "link-arg=/OPT:ICF",
]
